/* TESTIMONIAL */
export const GET_TESTIMONIAL = "GET_TESTIMONIAL"
export const GET_TESTIMONIAL_SUCCESS = "GET_TESTIMONIAL_SUCCESS"
export const GET_TESTIMONIAL_FAIL = "GET_TESTIMONIAL_FAIL" 


/**
 * add TESTIMONIAL
 */
export const ADD_NEW_TESTIMONIAL = "ADD_NEW_TESTIMONIAL"
export const ADD_TESTIMONIAL_SUCCESS = "ADD_TESTIMONIAL_SUCCESS"
export const ADD_TESTIMONIAL_FAIL = "ADD_TESTIMONIAL_FAIL"


/**
 * Edit TESTIMONIAL
 */
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL"
export const UPDATE_TESTIMONIAL_SUCCESS = "UPDATE_TESTIMONIAL_SUCCESS"
export const UPDATE_TESTIMONIAL_FAIL = "UPDATE_TESTIMONIAL_FAIL"

/**
 * Delete TESTIMONIAL
 */
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL"
export const DELETE_TESTIMONIAL_SUCCESS = "DELETE_TESTIMONIAL_SUCCESS"
export const DELETE_TESTIMONIAL_FAIL = "DELETE_TESTIMONIAL_FAIL"

