/* TEMPLATELIBRARY */
export const GET_TEMPLATELIBRARY = "GET_TEMPLATELIBRARY"
export const GET_TEMPLATELIBRARY_SUCCESS = "GET_TEMPLATELIBRARY_SUCCESS"
export const GET_TEMPLATELIBRARY_FAIL = "GET_TEMPLATELIBRARY_FAIL" 

/**
 * add TEMPLATELIBRARY
 */
export const ADD_NEW_TEMPLATELIBRARY = "ADD_NEW_TEMPLATELIBRARY"
export const ADD_TEMPLATELIBRARY_SUCCESS = "ADD_TEMPLATELIBRARY_SUCCESS"
export const ADD_TEMPLATELIBRARY_FAIL = "ADD_TEMPLATELIBRARY_FAIL"

/**
 * Edit TEMPLATELIBRARY
 */
export const UPDATE_TEMPLATELIBRARY = "UPDATE_TEMPLATELIBRARY"
export const UPDATE_TEMPLATELIBRARY_SUCCESS = "UPDATE_TEMPLATELIBRARY_SUCCESS"
export const UPDATE_TEMPLATELIBRARY_FAIL = "UPDATE_TEMPLATELIBRARY_FAIL"

/**
 * Delete TEMPLATELIBRARY
 */
export const DELETE_TEMPLATELIBRARY = "DELETE_TEMPLATELIBRARY"
export const DELETE_TEMPLATELIBRARY_SUCCESS = "DELETE_TEMPLATELIBRARY_SUCCESS"
export const DELETE_TEMPLATELIBRARY_FAIL = "DELETE_TEMPLATELIBRARY_FAIL"

/* LIBRARY_CATEGORY */
export const GET_LIBRARY_CATEGORY = "GET_LIBRARY_CATEGORY"
export const GET_LIBRARY_CATEGORY_SUCCESS = "GET_LIBRARY_CATEGORY_SUCCESS"
export const GET_LIBRARY_CATEGORY_FAIL = "GET_LIBRARY_CATEGORY_FAIL" 

/**
 * add  LIBRARY_CATEGORY
 */
export const ADD_NEW_LIBRARY_CATEGORY = "ADD_NEW_LIBRARY_CATEGORY"
export const ADD_LIBRARY_CATEGORY_SUCCESS = "ADD_LIBRARY_CATEGORY_SUCCESS"
export const ADD_LIBRARY_CATEGORY_FAIL = "ADD_LIBRARY_CATEGORY_FAIL"

/**
 * Edit LIBRARY_CATEGORY
 */
export const UPDATE_LIBRARY_CATEGORY = "UPDATE_LIBRARY_CATEGORY"
export const UPDATE_LIBRARY_CATEGORY_SUCCESS = "UPDATE_LIBRARY_CATEGORY_SUCCESS"
export const UPDATE_LIBRARY_CATEGORY_FAIL = "UPDATE_LIBRARY_CATEGORY_FAIL"

/**
 * Delete LIBRARY_CATEGORY
 */
export const DELETE_LIBRARY_CATEGORY = "DELETE_LIBRARY_CATEGORY"
export const DELETE_LIBRARY_CATEGORY_SUCCESS = "DELETE_LIBRARY_CATEGORY_SUCCESS"
export const DELETE_LIBRARY_CATEGORY_FAIL = "DELETE_LIBRARY_CATEGORY_FAIL"