//  Broadcast 
export const GET_BROADCAST = "GET_BROADCAST"
export const GET_BROADCAST_SUCCESS = "GET_BROADCAST_SUCCESS"
export const GET_BROADCAST_FAIL = "GET_BROADCAST_FAIL"


export const ADD_NEW_BROADCAST = "ADD_BROADCAST_SUCCESS"
export const ADD_BROADCAST_SUCCESS = "ADD_BROADCAST_SUCCESS"
export const ADD_BROADCAST_FAIL = "ADD_BROADCAST_FAIL"  


/* Broadcast DETAIL*/
export const GET_BROADCAST_DETAIL = "GET_BROADCAST_DETAIL"
export const GET_BROADCAST_DETAIL_SUCCESS = "GET_BROADCAST_DETAIL_SUCCESS"
export const GET_BROADCAST_DETAIL_FAIL = "GET_BROADCAST_DETAIL_FAIL" 


 /**
  * Edit user
  */
 export const UPDATE_BROADCAST = "UPDATE_BROADCAST"
 export const UPDATE_BROADCAST_SUCCESS = "UPDATE_BROADCAST_SUCCESS"
 export const UPDATE_BROADCAST_FAIL = "UPDATE_BROADCAST_FAIL"
 
 /**
  * Delete user
  */
 export const DELETE_BROADCAST = "DELETE_BROADCAST"
 export const DELETE_BROADCAST_SUCCESS = "DELETE_BROADCAST_SUCCESS"
 export const DELETE_BROADCAST_FAIL = "DELETE_BROADCAST_FAIL"