//  Templates 
export const GET_TEMPLATES = "GET_TEMPLATES"
export const GET_TEMPLATES_SUCCESS = "GET_TEMPLATES_SUCCESS"
export const GET_TEMPLATES_FAIL = "GET_TEMPLATES_FAIL"


export const ADD_NEW_TEMPLATES = "ADD_TEMPLATES_SUCCESS"
export const ADD_TEMPLATES_SUCCESS = "ADD_TEMPLATES_SUCCESS"
export const ADD_TEMPLATES_FAIL = "ADD_TEMPLATES_FAIL"  


/* Templates DETAIL*/
export const GET_TEMPLATES_DETAIL = "GET_TEMPLATES_DETAIL"
export const GET_TEMPLATES_DETAIL_SUCCESS = "GET_TEMPLATES_DETAIL_SUCCESS"
export const GET_TEMPLATES_DETAIL_FAIL = "GET_TEMPLATES_DETAIL_FAIL" 


 /**
  * Edit user
  */
 export const UPDATE_TEMPLATES = "UPDATE_TEMPLATES"
 export const UPDATE_TEMPLATES_SUCCESS = "UPDATE_TEMPLATES_SUCCESS"
 export const UPDATE_TEMPLATES_FAIL = "UPDATE_TEMPLATES_FAIL"
 
 /**
  * Delete user
  */
 export const DELETE_TEMPLATES = "DELETE_TEMPLATES"
 export const DELETE_TEMPLATES_SUCCESS = "DELETE_TEMPLATES_SUCCESS"
 export const DELETE_TEMPLATES_FAIL = "DELETE_TEMPLATES_FAIL"